In [1]:
import numpy as np

In [16]:
data = np.genfromtxt('data/ratings.dat', delimiter="::", dtype=np.int64)
# strtemp = data[:, 1]
# ▼ 에러코드
# print(data[data[:,1], :])
# print(data.shape)

[[       10      2043         5 978228989]
 [        8       269         4 978231121]
 [       10       253         5 978228886]
 ...
 [        8      2916         5 978229172]
 [       10      2946         3 979168591]
 [       10       898         4 979167630]]


In [10]:
movie_ids = np.unique(data[:, 1])
print(movie_ids)

[   1    2    3 ... 3950 3951 3952]


In [11]:
mean_values = []
for movie_id in movie_ids:
    data_for_movie = data[data[:,1]==movie_id, : ]
    value = data_for_movie[:, 2].mean()
    mean_values.append([movie_id, value])

In [12]:
mean_values[:10]

[[1, 4.146846413095811],
 [2, 3.20114122681883],
 [3, 3.01673640167364],
 [4, 2.7294117647058824],
 [5, 3.0067567567567566],
 [6, 3.8787234042553194],
 [7, 3.410480349344978],
 [8, 3.014705882352941],
 [9, 2.656862745098039],
 [10, 3.5405405405405403]]

In [13]:
mean_array = np.array(mean_values, dtype=np.float32)
print(mean_array[:10])

[[ 1.         4.1468463]
 [ 2.         3.201141 ]
 [ 3.         3.0167365]
 [ 4.         2.7294118]
 [ 5.         3.0067568]
 [ 6.         3.8787234]
 [ 7.         3.4104803]
 [ 8.         3.014706 ]
 [ 9.         2.6568627]
 [10.         3.5405405]]


In [14]:
np.savetxt('data/movieid_result.csv', mean_array, fmt='%.2f', delimiter=',')