In [18]:
x_data1 = [[73., 80., 75.],
           [93., 88., 93.],
           [89., 91., 90.],
           [96., 98., 100.],
           [73., 66., 70.]]
t_data1 = [[152.], [185.], [180.], [196.], [142.]]

In [19]:
import numpy as np

In [20]:
x_data1 = np.array(x_data1)
t_data1 = np.array(t_data1)
print(x_data1)
print(t_data1)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [21]:
w = np.random.rand(3, 1)
b = np.random.rand(1)

print(w)
print(b)

[[0.51056375]
 [0.2509818 ]
 [0.82372376]]
[0.15246258]


In [22]:
def loss_func(x, t):
    y = np.dot(x, w) + b
    return (np.sum((t-y)**2)) / (len(x))

In [23]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x) # 미분값을 저장할 배열

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite']) # 2차 이상 배열을 반복자에 한줄로 만들어서 실어준다

    while not it.finished:
        idx = it.multi_index

        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x + delta_x)

        x[idx] = tmp_val - delta_x
        fx2 = f(x) #f(x - delta_x)

        grad[idx] = (fx1 - fx2) / (2*delta_x)

        x[idx] = tmp_val
        it.iternext()

    return grad

In [24]:
def predict(x):
  y=np.dot(x, w)+b
  return y

In [28]:
learning_rate=1e-5
f = lambda x: loss_func(x_data1, t_data1)
print('Initial error value =', loss_func(x_data1, t_data1), "Initial w = ", w, "b = ", b)

for step in range(200000):
    w -= learning_rate * numerical_derivative(f, w)
    b -= learning_rate*numerical_derivative(f, b)

    if step % 400 == 0:
        print('step :', step, 'error value : ', loss_func(x_data1, t_data1), 'w=',w, 'b=', b)

Initial error value = 0.3451325897476902 Initial w =  [[0.83500691]
 [0.41606555]
 [0.75638217]] b =  [0.18638528]
step : 0 error value :  0.3451236408573328 w= [[0.83501199]
 [0.41606804]
 [0.75637468]] b= [0.18638648]
step : 400 error value :  0.3415786637277546 w= [[0.83703252]
 [0.41705921]
 [0.75339312]] b= [0.18686123]
step : 800 error value :  0.33810178379514155 w= [[0.83903253]
 [0.41804195]
 [0.75044021]] b= [0.18733243]
step : 1200 error value :  0.33469168981496866 w= [[0.84101232]
 [0.41901623]
 [0.74751567]] b= [0.18780011]
step : 1600 error value :  0.33134709619413844 w= [[0.84297218]
 [0.41998203]
 [0.74461927]] b= [0.18826429]
step : 2000 error value :  0.32806674241077616 w= [[0.84491238]
 [0.42093931]
 [0.74175074]] b= [0.18872502]
step : 2400 error value :  0.324849392462245 w= [[0.84683317]
 [0.42188809]
 [0.73890984]] b= [0.18918233]
step : 2800 error value :  0.32169383433729115 w= [[0.8487348 ]
 [0.42282836]
 [0.73609631]] b= [0.18963625]
step : 3200 error valu

In [30]:
predict(np.array([[80, 85, 100], [100, 90, 85]]))

array([[172.72799033],
       [189.30655487]])