In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
# random status : 랜덤한 값이 같은 값으로 계속 나온다
torch.manual_seed(1)
x_train = torch.FloatTensor([[1],[2],[3],[4],[5]])
y_train = torch.FloatTensor([[3],[5],[7],[9],[11]])

In [4]:
model = nn.Linear(1,1) # input_dim, output_dim : 입력 자료의 차원, 출력 자료의 차원
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [6]:
optimize = optim.SGD(model.parameters(), lr=0.01)

In [9]:
for epoch in range(20000 + 1):
    predict = model(x_train)
    cost = F.mse_loss(predict, y_train)

    optimize.zero_grad() # optimize 초기화
    cost.backward() # 손실함수는 계산된 결과에서 앞으로 돌아온다 그래서 backward() 처리한다. / cost 계산 적용
    optimize.step() # w, b를 업데이트 한다.

    if epoch % 100 == 0:
        print('epoch', epoch, 'Cost :', cost.item())

epoch 0 Cost : 2.1742694400472828e-07
epoch 100 Cost : 1.10456042534679e-07
epoch 200 Cost : 5.6271755255465905e-08
epoch 300 Cost : 2.85126589005813e-08
epoch 400 Cost : 1.4568525052993664e-08
epoch 500 Cost : 7.422113590394019e-09
epoch 600 Cost : 3.761454259176844e-09
epoch 700 Cost : 1.9176240595442096e-09
epoch 800 Cost : 1.0085046131536046e-09
epoch 900 Cost : 5.371020850297725e-10
epoch 1000 Cost : 2.9467628337442875e-10
epoch 1100 Cost : 1.652210868119397e-10
epoch 1200 Cost : 1.0750227097400256e-10
epoch 1300 Cost : 6.230038707144558e-11
epoch 1400 Cost : 5.426272625674855e-11
epoch 1500 Cost : 5.426272625674855e-11
epoch 1600 Cost : 5.426272625674855e-11
epoch 1700 Cost : 5.426272625674855e-11
epoch 1800 Cost : 5.426272625674855e-11
epoch 1900 Cost : 5.426272625674855e-11
epoch 2000 Cost : 5.426272625674855e-11
epoch 2100 Cost : 5.426272625674855e-11
epoch 2200 Cost : 5.426272625674855e-11
epoch 2300 Cost : 5.426272625674855e-11
epoch 2400 Cost : 5.426272625674855e-11
epoch 2

In [10]:
print(list(model.parameters()))

[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [11]:
model(torch.FloatTensor([[7],[9]]))

tensor([[15.0000],
        [19.0000]], grad_fn=<AddmmBackward0>)