In [1]:
import torch

In [6]:
print(torch.tensor([1,2,3,4,5]))
print(torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int64))
print(torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float64))

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [5]:
ft = torch.FloatTensor([[1,2,3],[4,5,6]])
print(ft)
lt = torch.LongTensor([[1,2,3],[4,5,6]])
print(lt)
bt = torch.ByteTensor([[1,0],[0,1]])
print(bt)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)
