In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [21]:
import numpy as np
import pandas as pd

In [22]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df=pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
raw_df

0      1      2    3      4      5     6       7    8      9   \
0       0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
2       0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3     396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
4       0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
...         ...    ...    ...  ...    ...    ...   ...     ...  ...    ...   
1007  396.90000   5.64  23.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1008    0.10959   0.00  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
1009  393.45000   6.48  22.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1010    0.04741   0.00  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
1011  396.90000   7.88  11.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   

        10  
0     15.3  
1      NaN  
2     17.8  
3      NaN  
4     17.8  
...    ...  
1007   NaN  
1008  21.0  
1009   NaN  
1010  21.0  
1011   NaN  

[1012 rows x 11 columns]

In [84]:
torch.manual_seed(1)
data=np.hstack([raw_df.values[::2, :], raw_df.values[1::2,:2]])
x_data = torch.FloatTensor(data)
print(x_data)
print(x_data.size())
# x 값 받기
ax = x_data.size()[1]

tensor([[6.3200e-03, 1.8000e+01, 2.3100e+00,  ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00,  ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00,  ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01,  ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01,  ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01,  ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]])
torch.Size([506, 13])


In [87]:
target=raw_df.values[1::2, 2]
y_data = torch.FloatTensor(target)
y_data = y_data.view(506,1)
print(y_data)
print(y_data.size())
#y 값 받기
ay = y_data.size()[1]

tensor([[24.0000],
        [21.6000],
        [34.7000],
        [33.4000],
        [36.2000],
        [28.7000],
        [22.9000],
        [27.1000],
        [16.5000],
        [18.9000],
        [15.0000],
        [18.9000],
        [21.7000],
        [20.4000],
        [18.2000],
        [19.9000],
        [23.1000],
        [17.5000],
        [20.2000],
        [18.2000],
        [13.6000],
        [19.6000],
        [15.2000],
        [14.5000],
        [15.6000],
        [13.9000],
        [16.6000],
        [14.8000],
        [18.4000],
        [21.0000],
        [12.7000],
        [14.5000],
        [13.2000],
        [13.1000],
        [13.5000],
        [18.9000],
        [20.0000],
        [21.0000],
        [24.7000],
        [30.8000],
        [34.9000],
        [26.6000],
        [25.3000],
        [24.7000],
        [21.2000],
        [19.3000],
        [20.0000],
        [16.6000],
        [14.4000],
        [19.4000],
        [19.7000],
        [20.5000],
        [25.

In [88]:
class MultiLinearRegressionModel(nn.Module):
    # 생성자 생성 : 생성자에서는 모델을 정의한다.
    def __init__(self, ax, ay):
        super().__init__()
        self.linear = nn.Linear(ax,ay)
    
    # 정의한 모델 실행
    def forward(self, x):
        return self.linear(x)

In [90]:
model = MultiLinearRegressionModel(ax, ay)
optimizer = optim.SGD(model.parameters(), lr=1e-7)

In [93]:
for epoch in range(200001):
    prediction = model(x_data)
    cost = F.mse_loss(prediction, y_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print('Epoch: ', epoch, 'cost :', cost.item())

Epoch:  0 cost : 45.68122482299805
Epoch:  400 cost : 45.676082611083984
Epoch:  800 cost : 45.671104431152344
Epoch:  1200 cost : 45.666133880615234
Epoch:  1600 cost : 45.66116714477539
Epoch:  2000 cost : 45.65619659423828
Epoch:  2400 cost : 45.65122985839844
Epoch:  2800 cost : 45.646270751953125
Epoch:  3200 cost : 45.64134216308594
Epoch:  3600 cost : 45.636436462402344
Epoch:  4000 cost : 45.63154220581055
Epoch:  4400 cost : 45.626651763916016
Epoch:  4800 cost : 45.62175750732422
Epoch:  5200 cost : 45.61687088012695
Epoch:  5600 cost : 45.61198425292969
Epoch:  6000 cost : 45.60710906982422
Epoch:  6400 cost : 45.602230072021484
Epoch:  6800 cost : 45.597354888916016
Epoch:  7200 cost : 45.59248733520508
Epoch:  7600 cost : 45.58762741088867
Epoch:  8000 cost : 45.582759857177734
Epoch:  8400 cost : 45.57789993286133
Epoch:  8800 cost : 45.57305145263672
Epoch:  9200 cost : 45.56820297241211
Epoch:  9600 cost : 45.563350677490234
Epoch:  10000 cost : 45.558509826660156
Epoch

In [94]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-9.1726e-02,  1.0178e-01, -6.2935e-02,  1.6872e-01, -2.4285e-01,
          7.5043e-01,  1.1482e-01,  1.3079e-01,  7.2999e-02,  4.1019e-04,
          3.7374e-01,  3.0988e-02, -7.6551e-01]], requires_grad=True), Parameter containing:
tensor([-0.0556], requires_grad=True)]
