In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
x_train = [[73., 80., 75.],
           [93., 88., 93.],
           [89., 91., 90.],
           [96., 98., 100.],
           [73., 66., 70.]]
y_train = [[152.], [185.], [180.], [196.], [142.]]

In [3]:
# __init__ 와 forward를 정해져 있음
class MultiLinearRegressionModel(nn.Module):
    # 생성자 생성 : 생성자에서는 모델을 정의한다.
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
    
    # 정의한 모델 실행
    def forward(self, x):
        return self.linear(x)

In [4]:
torch.manual_seed(1)
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train)

In [5]:
model = MultiLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [13]:
for epoch in range(20001):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print('Epoch: ', epoch, 'cost :', cost.item())

Epoch:  0 cost : 0.1602286696434021
Epoch:  400 cost : 0.16019795835018158
Epoch:  800 cost : 0.16015425324440002
Epoch:  1200 cost : 0.16012263298034668
Epoch:  1600 cost : 0.1600874364376068
Epoch:  2000 cost : 0.16005156934261322
Epoch:  2400 cost : 0.16002318263053894
Epoch:  2800 cost : 0.15999609231948853
Epoch:  3200 cost : 0.15995731949806213
Epoch:  3600 cost : 0.15992963314056396
Epoch:  4000 cost : 0.15990376472473145
Epoch:  4400 cost : 0.15987364947795868
Epoch:  4800 cost : 0.15984033048152924
Epoch:  5200 cost : 0.15982060134410858
Epoch:  5600 cost : 0.1597871482372284
Epoch:  6000 cost : 0.1597646176815033
Epoch:  6400 cost : 0.1597367376089096
Epoch:  6800 cost : 0.15971218049526215
Epoch:  7200 cost : 0.15968552231788635
Epoch:  7600 cost : 0.1596594750881195
Epoch:  8000 cost : 0.15963450074195862
Epoch:  8400 cost : 0.15961316227912903
Epoch:  8800 cost : 0.15958881378173828
Epoch:  9200 cost : 0.15956710278987885
Epoch:  9600 cost : 0.15954233705997467
Epoch:  100

In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.0263, 0.5117, 0.4714]], requires_grad=True), Parameter containing:
tensor([0.3131], requires_grad=True)]


In [15]:
model(torch.FloatTensor([[85, 76, 90]]))

tensor([[168.8634]], grad_fn=<AddmmBackward0>)