In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from sklearn import datasets

iris = datasets.load_iris()
print(iris.data)
print(iris.target)
print(iris.data.shape)
print(iris.target.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [2]:
x_train = torch.FloatTensor(iris.data)
y_train = torch.LongTensor(iris.target)
torch.manual_seed(1)

- python 기본 소스로 모델 작성
- 클래스로 모델 작성

In [3]:
y = torch.randint(5, (150,)).long()
print(y)

tensor([0, 4, 4, 3, 3, 3, 1, 1, 4, 2, 3, 4, 1, 3, 3, 0, 2, 1, 2, 1, 0, 3, 1, 4,
        3, 1, 4, 2, 4, 4, 3, 1, 2, 3, 2, 3, 3, 1, 2, 0, 0, 4, 0, 3, 3, 0, 3, 4,
        1, 4, 4, 0, 3, 0, 1, 3, 1, 4, 2, 3, 1, 4, 4, 3, 3, 3, 1, 2, 2, 3, 4, 3,
        0, 2, 2, 3, 0, 4, 4, 0, 1, 2, 2, 0, 0, 0, 4, 1, 1, 4, 0, 3, 2, 2, 3, 2,
        2, 2, 2, 2, 3, 3, 3, 1, 1, 1, 0, 0, 2, 0, 3, 0, 0, 4, 4, 2, 0, 0, 3, 0,
        2, 1, 4, 2, 4, 4, 3, 4, 2, 1, 4, 1, 3, 4, 3, 3, 1, 2, 4, 4, 1, 2, 2, 0,
        0, 4, 3, 4, 1, 0])


In [4]:
y_one_hat = torch.zeros(150,3)
print(y_one_hat)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0

In [5]:
print(y_train.unsqueeze(1))
y_one_hat.scatter_(1, y_train.unsqueeze(1), 1)


tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],

tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1

In [6]:
print(y_train[:5])
print(y_one_hat[:5])

tensor([0, 0, 0, 0, 0])
tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [7]:
w = torch.zeros((4, 3), requires_grad=True) # 4, 3 : 3은 3가지의 방법을 의미
b = torch.zeros((1, 3), requires_grad=True)

In [10]:
pred = F.softmax(x_train.matmul(w)+b, dim=1).argmax(dim=1)
acuracy = (pred == y_train).sum() / len(pred)
print(acuracy)

tensor(0.9800)


In [8]:
optimizer = optim.SGD([w, b], lr=0.1)

In [9]:
for epoch in range(10001):
    y_hat = F.softmax(x_train.matmul(w)+b, dim=1)
    cost = (y_one_hat * -torch.log(y_hat)).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print("Epoch : {} Cost : {}".format(epoch, cost.item()))

Epoch : 0 Cost : 1.0986123085021973


Epoch : 400 Cost : 0.19145387411117554
Epoch : 800 Cost : 0.1388542205095291
Epoch : 1200 Cost : 0.11657103151082993
Epoch : 1600 Cost : 0.10395903140306473
Epoch : 2000 Cost : 0.09572090208530426
Epoch : 2400 Cost : 0.08985582739114761
Epoch : 2800 Cost : 0.08543255180120468
Epoch : 3200 Cost : 0.08195575326681137
Epoch : 3600 Cost : 0.0791364312171936
Epoch : 4000 Cost : 0.07679388672113419
Epoch : 4400 Cost : 0.07480911165475845
Epoch : 4800 Cost : 0.07310032844543457
Epoch : 5200 Cost : 0.07160933315753937
Epoch : 5600 Cost : 0.07029359042644501
Epoch : 6000 Cost : 0.06912112236022949
Epoch : 6400 Cost : 0.06806758046150208
Epoch : 6800 Cost : 0.06711391359567642
Epoch : 7200 Cost : 0.06624507158994675
Epoch : 7600 Cost : 0.06544894725084305
Epoch : 8000 Cost : 0.06471569836139679
Epoch : 8400 Cost : 0.06403731554746628
Epoch : 8800 Cost : 0.06340707093477249
Epoch : 9200 Cost : 0.06281936913728714
Epoch : 9600 Cost : 0.062269482761621475
Epoch : 10000 Cost : 0.06175338104367256


In [16]:
class SoftmaxClassModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4,3)

    def forward(self, x):
        return self.linear(x)

In [17]:
model = SoftmaxClassModel()
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [18]:
for epoch in range(10001):
    y_hat = model(x_train)
    cost = F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        accuracy = (y_hat.argmax(dim=1) == y_train).sum()/len(y_hat)
        print("Epoch : {} Cost: {}  Accuracy : {}".format(epoch, cost.item(), accuracy))

Epoch : 0 Cost: 3.3348660469055176  Accuracy : 0.3333333432674408
Epoch : 400 Cost: 0.19346027076244354  Accuracy : 0.9733333587646484
Epoch : 800 Cost: 0.14058150351047516  Accuracy : 0.9800000190734863
Epoch : 1200 Cost: 0.1180357113480568  Accuracy : 0.9800000190734863
Epoch : 1600 Cost: 0.1052480936050415  Accuracy : 0.9866666793823242
Epoch : 2000 Cost: 0.0968853011727333  Accuracy : 0.9866666793823242
Epoch : 2400 Cost: 0.09092602133750916  Accuracy : 0.9866666793823242
Epoch : 2800 Cost: 0.08642793446779251  Accuracy : 0.9866666793823242
Epoch : 3200 Cost: 0.08288944512605667  Accuracy : 0.9866666793823242
Epoch : 3600 Cost: 0.08001775294542313  Accuracy : 0.9733333587646484
Epoch : 4000 Cost: 0.07762984931468964  Accuracy : 0.9733333587646484
Epoch : 4400 Cost: 0.07560506463050842  Accuracy : 0.9733333587646484
Epoch : 4800 Cost: 0.0738605409860611  Accuracy : 0.9800000190734863
Epoch : 5200 Cost: 0.07233726978302002  Accuracy : 0.9800000190734863
Epoch : 5600 Cost: 0.070992082