In [29]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [41]:
x_train = [[73., 80., 75.],
           [93., 88., 93.],
           [89., 91., 90.],
           [96., 98., 100.],
           [73., 66., 70.]]
y_train = [[152.], [185.], [180.], [196.], [142.]]

In [45]:
torch.manual_seed(1)
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train)

In [17]:
# model = nn.Linear(in_features=3, out_features=1) # input_dim, output_dim : 입력 자료의 차원, 출력 자료의 차원
# print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.5070, -0.0962,  0.2471]], requires_grad=True), Parameter containing:
tensor([-0.2683], requires_grad=True)]


In [42]:
# W와 B 값 확인하기
model = nn.Linear(3,1) # input_dim, output_dim : 입력 자료의 차원, 출력 자료의 차원
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.5435,  0.3462, -0.1188]], requires_grad=True), Parameter containing:
tensor([0.2937], requires_grad=True)]


In [43]:
optimize = optim.SGD(model.parameters(), lr=1e-5)

In [49]:
for epoch in range(20001):
    predict = model(x_train)
    cost = F.mse_loss(predict, y_train)

    optimize.zero_grad() # optimize 초기화
    cost.backward() # 손실함수는 계산된 결과에서 앞으로 돌아온다 그래서 backward() 처리한다. / cost 계산 적용
    optimize.step() # w, b를 업데이트 한다.

    if epoch % 100 == 0:
        print('epoch', epoch, 'Cost :', cost.item())

epoch 0 Cost : 0.24696040153503418
epoch 100 Cost : 0.24652092158794403
epoch 200 Cost : 0.24606695771217346
epoch 300 Cost : 0.24563975632190704
epoch 400 Cost : 0.24520210921764374
epoch 500 Cost : 0.24476225674152374
epoch 600 Cost : 0.2443244457244873
epoch 700 Cost : 0.2439001500606537
epoch 800 Cost : 0.24347898364067078
epoch 900 Cost : 0.24304714798927307
epoch 1000 Cost : 0.24262650310993195
epoch 1100 Cost : 0.2422020435333252
epoch 1200 Cost : 0.24178752303123474
epoch 1300 Cost : 0.2413775473833084
epoch 1400 Cost : 0.24095866084098816
epoch 1500 Cost : 0.24054686725139618
epoch 1600 Cost : 0.24014350771903992
epoch 1700 Cost : 0.23973505198955536
epoch 1800 Cost : 0.23932857811450958
epoch 1900 Cost : 0.23892664909362793
epoch 2000 Cost : 0.23852908611297607
epoch 2100 Cost : 0.23813402652740479
epoch 2200 Cost : 0.23773403465747833
epoch 2300 Cost : 0.2373465597629547
epoch 2400 Cost : 0.2369551956653595
epoch 2500 Cost : 0.23656506836414337
epoch 2600 Cost : 0.2361789196

In [50]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9463, 0.4719, 0.5894]], requires_grad=True), Parameter containing:
tensor([0.3440], requires_grad=True)]


In [51]:
# 예측을 해보자
new_bar = torch.FloatTensor([[73,80,75]])
pred = model(new_bar)
print(pred)

tensor([[151.3821]], grad_fn=<AddmmBackward0>)


- 파이썬 클래스 이용해서 구현

In [52]:
torch.manual_seed(1)
x_train = torch.FloatTensor([[1],[2],[3],[4],[5]])
y_train = torch.FloatTensor([[3],[5],[7],[9],[11]])

In [53]:
class LinearRegressionModel(nn.Module):
    # 생성자 생성 : 생성자에서는 모델을 정의한다.
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)
    
    # 정의한 모델 실행
    def forward(self, x):
        return self.linear(x)


In [54]:
model = LinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [55]:
for epoch in range(20001):
    prediction = model(x_train) # 예측
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print('Epoch: ', epoch, 'cost: ', cost.item())

Epoch:  0 cost:  39.16685104370117
Epoch:  400 cost:  0.01109258271753788
Epoch:  800 cost:  0.0007385412463918328
Epoch:  1200 cost:  4.91717473778408e-05
Epoch:  1600 cost:  3.276181814726442e-06
Epoch:  2000 cost:  2.1860606125301274e-07
Epoch:  2400 cost:  1.4702209227834828e-08
Epoch:  2800 cost:  9.986707016906848e-10
Epoch:  3200 cost:  1.0809344391793374e-10
Epoch:  3600 cost:  5.426272625674855e-11
Epoch:  4000 cost:  5.426272625674855e-11
Epoch:  4400 cost:  5.426272625674855e-11
Epoch:  4800 cost:  5.426272625674855e-11
Epoch:  5200 cost:  5.426272625674855e-11
Epoch:  5600 cost:  5.426272625674855e-11
Epoch:  6000 cost:  5.426272625674855e-11
Epoch:  6400 cost:  5.426272625674855e-11
Epoch:  6800 cost:  5.426272625674855e-11
Epoch:  7200 cost:  5.426272625674855e-11
Epoch:  7600 cost:  5.426272625674855e-11
Epoch:  8000 cost:  5.426272625674855e-11
Epoch:  8400 cost:  5.426272625674855e-11
Epoch:  8800 cost:  5.426272625674855e-11
Epoch:  9200 cost:  5.426272625674855e-11
E

In [58]:
print(list(model.parameters()))

[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [59]:
model(torch.FloatTensor([[11], [12]]))

tensor([[23.0000],
        [25.0000]], grad_fn=<AddmmBackward0>)