In [1]:
import numpy as np

In [2]:
x_data = np.array([1,2,3,4,5]).reshape(5,1)
y_data = np.array([3,5,7,9,11]).reshape(5,1)  # y = 2x + 1
print(x_data)
print(y_data)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [23]:
x_data1 = np.array([[1,2], [2,3], [3,4], [4,5], [5,6]]).reshape(5,2)
y_data1 = np.array([3,5,7,9,11]).reshape(5,1)

In [24]:
w1 = np.random.rand(2,1)
b1 = np.random.rand(1)

In [3]:
w = np.random.rand(1,1) # y = Wx + b 를 y = xw + b 로 계산을 한다.
b = np.random.rand(1)
print(w, b)

[[0.89591418]] [0.3489733]


In [17]:
# def loss_func(x, t):
#     y = np.dot(x, w) + b
#     return (np.sum((t-y)**2)) / (len(x))

In [26]:
def loss_func(x, t):
    y = np.dot(x, w1) + b1
    return (np.sum((t-y)**2)) / (len(x))

In [5]:
# 편미분
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite']) #

    while not it.finished:
        idx = it.multi_index

        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x + delta_x)

        x[idx] = tmp_val - delta_x
        fx2 = f(x) #f(x - delta_x)

        grad[idx] = (fx1 - fx2) / (2*delta_x)

        x[idx] = tmp_val
        it.iternext()

    return grad

In [21]:
# 예측함수
def predict(x):
  y=np.dot(x, w)+b
  return y

In [27]:
def predict1(x):
    y = np.dot(x, w1) + b1
    return y

In [20]:
learning_rate=1e-2 # 1e - 2 : 1 * 10의 제곱을 의미 
f = lambda x: loss_func(x_data, y_data)
print("Initial error value =", loss_func(x_data, y_data), "Initial w = ", w, "b = ", b)

for step in range(2000):
    w -= learning_rate * numerical_derivative(f, w)
    b -= learning_rate * numerical_derivative(f, b)

    if step % 100 == 0:
        print('step :', step, 'error value : ', loss_func(x_data, y_data), 'w=',w, 'b=', b)

Initial error value = 2.9149728434702625e-08 Initial w =  [[2.00011087]] b =  [0.99959982]
step : 0 error value :  2.8949873171323095e-08 w= [[2.00011049]] b= [0.9996012]
step : 100 error value :  1.454996322119555e-08 w= [[2.00007833]] b= [0.99971727]
step : 200 error value :  7.312689367731682e-09 w= [[2.00005553]] b= [0.99979956]
step : 300 error value :  3.675296286051773e-09 w= [[2.00003937]] b= [0.9998579]
step : 400 error value :  1.8471730591451662e-09 w= [[2.00002791]] b= [0.99989926]
step : 500 error value :  9.283736724567946e-10 w= [[2.00001979]] b= [0.99992858]
step : 600 error value :  4.665928140518453e-10 w= [[2.00001403]] b= [0.99994937]
step : 700 error value :  2.3450563128948516e-10 w= [[2.00000994]] b= [0.99996411]
step : 800 error value :  1.1786056160581356e-10 w= [[2.00000705]] b= [0.99997455]
step : 900 error value :  5.923572882541221e-11 w= [[2.000005]] b= [0.99998196]
step : 1000 error value :  2.977138002312327e-11 w= [[2.00000354]] b= [0.99998721]
step : 1

In [29]:
# 값이 클때 발산을 할 수 있어서 손실 함수가 늘어난다.
# 값이 작으면 데이터를 구할때 시간이 많이 소모된다.
# 가설로 정한 그래프가 직선으로 내려오는게 아니고 구불 구불한 곡선이 되면 
# 중간의 평평한 지점을 기울기 0으로 오류를 발생을 할 수 있다. 이렇게 되면 잘못된 결과 값이 나온다.
learning_rate=1e-2 
f = lambda x: loss_func(x_data1, y_data1)
print("Initial error value =", loss_func(x_data1, y_data1), "Initial w = ", w1, "b = ", b1)

for step in range(2000):
    w1 -= learning_rate * numerical_derivative(f, w1)
    b1 -= learning_rate*numerical_derivative(f, b1)

    if step % 100 == 0:
        print('step :', step, 'error value : ', loss_func(x_data1, y_data1), 'w=',w1, 'b=', b1)

Initial error value = 2.826918611731517 Initial w =  [[0.90189919]
 [0.65854489]] b =  [0.09791295]
step : 0 error value :  0.4848113081341687 w= [[1.01321403]
 [0.80110392]] b= [0.11107353]
step : 100 error value :  4.0178457529126334e-05 w= [[1.0957065 ]
 [0.90010861]] b= [0.11471583]
step : 200 error value :  1.7777323342499086e-05 w= [[1.09827492]
 [0.89894139]] b= [0.11091947]
step : 300 error value :  7.865738125825434e-06 w= [[1.09998337]
 [0.89816499]] b= [0.10839422]
step : 400 error value :  3.4802672523922006e-06 w= [[1.10111979]
 [0.89764854]] b= [0.10671448]
step : 500 error value :  1.5398758456366198e-06 w= [[1.10187571]
 [0.89730502]] b= [0.10559716]
step : 600 error value :  6.813320495290869e-07 w= [[1.10237852]
 [0.89707651]] b= [0.10485395]
step : 700 error value :  3.0146155161116684e-07 w= [[1.10271299]
 [0.89692452]] b= [0.10435958]
step : 800 error value :  1.333844006937795e-07 w= [[1.10293547]
 [0.89682341]] b= [0.10403074]
step : 900 error value :  5.90171391

In [22]:
predict(np.array([7]))

array([15.00000039])