In [1]:
import numpy as np
import torch
import torch.nn as nn
torch.manual_seed(777)

In [6]:
x = torch.FloatTensor([[0,0], [0,1], [1,0], [1,1]])
y = torch.FloatTensor([[0], [1], [1], [1]]) # XOR 는 값이 다르게 나옴

In [7]:
model = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
)

In [8]:
criterion = torch.nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [9]:
for epoch in range(1001):
    h_hat = model(x)
    cost = criterion(h_hat, y)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print("Epoch : {}  Cost : {}".format(epoch, cost.item()))


Epoch : 0  Cost : 0.9125369787216187
Epoch : 100  Cost : 0.09084385633468628
Epoch : 200  Cost : 0.04733480140566826
Epoch : 300  Cost : 0.031634144484996796
Epoch : 400  Cost : 0.02365809679031372
Epoch : 500  Cost : 0.018858935683965683
Epoch : 600  Cost : 0.015662875026464462
Epoch : 700  Cost : 0.013385098427534103
Epoch : 800  Cost : 0.01168129127472639
Epoch : 900  Cost : 0.010359501466155052
Epoch : 1000  Cost : 0.009304734878242016


In [10]:
with torch.no_grad():
    pred = model(x)
    predicted = (pred > 0.5).float()
    print(pred)
    print(predicted)

tensor([[0.0205],
        [0.9918],
        [0.9918],
        [1.0000]])
tensor([[0.],
        [1.],
        [1.],
        [1.]])


- 다층 퍼셉트론

In [2]:
x = torch.FloatTensor([[0,0], [0,1], [1,0], [1,1]])
y = torch.FloatTensor([[0], [1], [1], [0]]) # XOR 는 값이 다르게 나옴

In [10]:
model = nn.Sequential(
    # Linear(2, 10) : 2개의 입력값과 은닉층 첫번째 노드의 크기가 10개라는 의미
    # (input_dim=2, output_dim=10)
    nn.Linear(2,10, bias=True), 
    nn.Sigmoid(), 
    nn.Linear(10,10, bias=True), # 은닉층 : 10 / (input_dim=10, output_dim=10)
    nn.Sigmoid(),
    nn.Linear(10, 10),          # 은닉층 : 10 / (input_dim=10, output_dim=10)
    nn.Sigmoid(),
    nn.Linear(10, 1, bias=True),    # 출력층 : 1 / (input_dim=10, output_dim=1)
    nn.Sigmoid()
)

In [4]:
criterion1 = torch.nn.BCELoss() # BCELoss : 바이너리 크로스 손실함수
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [5]:
for epoch in range(100001):
    h_hat = model(x)
    cost = criterion1(h_hat, y)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()


    if epoch % 100 == 0:
        print("Epoch : {}  Cost : {}".format(epoch, cost.item()))

Epoch : 0  Cost : 0.6948983669281006
Epoch : 100  Cost : 0.693155825138092
Epoch : 200  Cost : 0.6931535601615906
Epoch : 300  Cost : 0.6931513547897339
Epoch : 400  Cost : 0.693149209022522
Epoch : 500  Cost : 0.6931473016738892
Epoch : 600  Cost : 0.6931453943252563
Epoch : 700  Cost : 0.6931434869766235
Epoch : 800  Cost : 0.6931416988372803
Epoch : 900  Cost : 0.6931397914886475
Epoch : 1000  Cost : 0.6931380033493042
Epoch : 1100  Cost : 0.6931361556053162
Epoch : 1200  Cost : 0.6931343078613281
Epoch : 1300  Cost : 0.6931324005126953
Epoch : 1400  Cost : 0.6931304931640625
Epoch : 1500  Cost : 0.6931284666061401
Epoch : 1600  Cost : 0.6931264400482178
Epoch : 1700  Cost : 0.6931242942810059
Epoch : 1800  Cost : 0.6931220889091492
Epoch : 1900  Cost : 0.6931197047233582
Epoch : 2000  Cost : 0.6931171417236328
Epoch : 2100  Cost : 0.6931145191192627
Epoch : 2200  Cost : 0.6931115984916687
Epoch : 2300  Cost : 0.6931084990501404
Epoch : 2400  Cost : 0.6931051015853882
Epoch : 2500  

In [6]:
with torch.no_grad():
    pred = model(x)
    predicted = (pred > 0.5).float()
    print(predicted)

tensor([[0.],
        [1.],
        [1.],
        [0.]])
